--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/cooldogedev/BedrockEconomy
build-by-default: true
branches:
- main
projects:
  BedrockEconomy:
    path: ""
    libs:
      - src: cooldogedev/libSQL/libSQL
        version: ^0.1.1
      - src: CortexPE/Commando/Commando
        version: ^3.0.0
        branch: PM4
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.0.0
    lint:
      phpstan: false
#      syntaxError: false
...

